### ISSUE TITLE
Bon Programming Language already exists

### ISSUE THREAD

**Issue by gywerd** [FBMachine/bon#15]
'Bon' was invented by the programming pioneer Kenneth Lane Thompson (inventor of 'B' & co-inventor of Unix), in 1969 and became precursors of the C language. It was named after his wife Bonnie according to himself (or the tibetan religion Bön according to his colleague Dennis Ritchie [inventor of C & co-inventor of Unix])

Honestly we don't need a new programming language. Rather we need a reunified, platform independent, aot-compiled, modernized 'C' based on the experience from ANSI C, C++, C--, Objective C, C#, JAVA, Go etc.

**Comment by daniel-p-gonzalez** [comment]
"Rather we need a reunified, platform independent, aot-compiled, modernized 'C' based on the experience from ANSI C, C++, C--, Objective C, C#, JAVA, Go etc."

Sounds like you should be working on that instead of posting an issue here.

**Comment by gywerd** [comment]
Thompson, K.L. (1969). Bon Programming Language User's Manual. AT&T Bell Laboratories. Murray Hill, NJ:
https://people.csail.mit.edu/saltzer/Multics/MHP-Saltzer-060508/filedrawers/180.btl-misc/Scan%204.PDF

**Comment by daniel-p-gonzalez** [comment]
Not sure if you read the readme in this repo, but I made it clear in the "why another programming language" section that it is named after my mother, who passed away around this time 3 years ago. You are certainly entitled to your opinion about whether we need another programming language, but surely you can respect someone creating one to honor a lost loved one.

I can see that you really care about the name clash, but do keep in mind that neither programming language is actually used by anyone. I'm not meaning to disrespect Ken Thompson by using the same name, but there is no way I would ever rename the project.

I closed the issue not to disrespect you either, I just don't understand what you actually expect me to do. Delete the repository?
