### ISSUE TITLE
Differences to crystal

### ISSUE THREAD

**Issue by pannous** [FBMachine/bon#5]
What are the main conceptual differences to crystal?

**Comment by spencerwi** [comment]
As someone who writes a decent amount of Crystal (and not this language's author), it looks like the "class" system is different; Bon appears to use Haskell-style typeclasses for ad-hoc polymorphism, while Crystal is the more traditional, Ruby-style OOP.

I'd describe Crystal as "typed and native-compiled Ruby", where at a glance here I'd describe Bon as "something between Haskell and OCaml, but with Ruby syntax"

**Comment by daniel-p-gonzalez** [comment]
@spencerwi is pretty spot on, though I would say the syntax in Bon aims to be more like Python with an 
 explicit `end` for blocks (and no `:`). At a superficial level this makes it appear Ruby-like, but Ruby has much more freedom (/ many variations) when it comes to syntax.
