### ISSUE TITLE
Benchmark sources

### ISSUE THREAD

**Issue by 0rvar** [FBMachine/bon#7]
Is there any chance you could publish the benchmarks so that I could try it out on my own machine and compare with more languages?

**Comment by daniel-p-gonzalez** [comment]
Sure thing. Keep in mind that Bon is in its infancy, so benchmarks at this point are more an attempt to keep performance in mind from the beginning, rather than being a serious head to head comparison.

**Comment by daniel-p-gonzalez** [comment]
Benchmarks have been added to the auto_mem branch if you want an early look:
https://github.com/FBMachine/bon/tree/auto_mem/benchmarks

This branch is under heavy development, so it may be some time before it gets merged into master. Note that the performance is a bit better now, as the optimization passes now match closer to clang.

**Comment by daniel-p-gonzalez** [comment]
This has been merged into master with #10:
https://github.com/FBMachine/bon/tree/master/benchmarks
